"""
test
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
import pendulum


default_args={
    "owner": "Michael Walker,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-02-09", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Michael Walker": "mailto:michael@brontecapital.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clsds2o5603wn01qj17yi1nx5/cloud-ide/clse5cxam042701rzfvd0u86a/clse5evm2041w01rl3k10puh2",
    },
)
def test():

dag_obj = test()
